### ISSUE TITLE
USER STORY: Creator View Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#108]
As a creator, I will want to have a page that allows me to create and view products so that I can manage my inventory on the app.

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/cdc6a97a-55e1-4b1e-a7d3-fe957a859a74)

Sign in and have Creator options available:
- Add product page link: Create an add product button that routes to the add product page allowing them to add products
- Create a View All Products button, routing them to the landing page where creator’s can view all products
- Sign out button and functionality on nav bar

**Comment by nickolasram** [comment]
With the pull request I just made, this user story should be finished. The only thing that needs to be worked on is routing to the edit user page which I think will happen once that page is done being implemented. Apologies for the delay on getting this User story done; I overlooked that I was assigned to it. Let me know if there's anything else I should work on for this page for now.

**Comment by taylorpapke** [comment]
@nickolasram The creator page is a separate page for users with the creator role. Admin view page is a separate page and is for users with the admin role. @Annelisebx was assigned to the admin view page as should be finishing it up.

**Comment by nickolasram** [comment]
@taylorpapke okay, I see. With the AdminView page working, a separate CreatorView page should be really quick and easy to implement using the AdminView page as a template. I have a couple questions before I get to that: is the only functional difference between the AdminView page and CreatorView page the Edit User button? Would it be more efficient to, instead of creating a whole new page, use the same page but simply show/hide that button depending based on the user’s role? Or do we foresee some larger differences being added in the future that would have it make more sense to have AdminView and CreatorView being separate pages?

**Comment by taylorpapke** [comment]
@nickolasram For now, let's implement it in the same way that it is done on nsc-events-android https://github.com/SeattleColleges/nsc-events-android/blob/main/app/src/main/java/com/example/nsc_events/screen/CreatorView.kt or by using admin page as a template to create a new page and remove the "edit user role" button. This will be better for the next team who will be working on these features as the pages intent will be clear and the same on both apps. 

Your idea is good but a structural change to our design (https://github.com/SeattleColleges/belindas-closet-android/wiki/Belinda's-Closet-Android-Wiki#belindas-closet-mobile-app-layout) would have to undergo review/approval from the leadership team and we have run out of time for this quarter. This would be a good thing to bring up in the winter quarter.
