### ISSUE TITLE
QA - Bug Hunt

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-android#49]
Feel free to list down your bug finds here. For now until a better approach is discussed, we will list all of our appropriate bugs that are discovered here.

Please provide the associated information:

**Method of Discovery**
IE: "I was clicking login, and my screen flickered and moved a div to the far side of my screen. My browser is Chrome Version 117.0.5938.132"

Don't hesitate to be as descriptive as possible so we can attempt to recreate the bug and work on a fix. You may also feel free to create a fix, but please document the solution, and let myself or someone else (PO, PM, Lead Dev, BC) know.

**Comment by intisarosman1** [comment]
**Method of Discovery**
When I enter my full email into the email field (example: intisar.osman@seattlecolleges.edu) on the login and registration page, I get an "Invalid email!" error because my email is longer than 30 characters. This means a user with a longer email cannot create an account or login.

**Comment by taylorpapke** [comment]
This issue is outdated since we've moved to our new user story format.
