### ISSUE TITLE
Create text to display product details

### ISSUE THREAD

**Issue by theGaryLarson** [SeattleColleges/belindas-closet-android#62]
Type, size, etc.

_Review the product data structure that is defined in belinda's nest.js_

[product data structure](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/schemas/product.schema.ts)

User story #61

**Comment by theGaryLarson** [comment]
Hi @intisarosman1 I can see why you need more information. Thanks for reaching out.

I have to have PO @taylorpapke confirm this but currently when clicking to view details it shows the 3 following properties:
* Name
* Size
* Description
There needs to be some logic added on the Detail View that checks the Name and assigns the correct size appropriately.
However, if a item such as shoes is listed the file in model/Product.kt does not support this.
![image](https://github.com/SeattleColleges/belindas-closet-android/assets/64063020/20db9121-ac08-4a5d-913d-80c79b687d3c)

* Please add to the Product.kt file to handle this option for shoes, pant size, etc. Often times pants are not a measurement such as XXS, XS, S, M, L, XL ... etc. but a waist size and in seam length. I know it varies from women and men sizing options. This needs to be accounted for in both the Product.kt file and in the Product Details View.

I hope this makes sense and you are comfortable adding options.
@tinpham5614 What do you think of removing the Sizes restriction for now until we can get this better defined from the Product Owner?

**Comment by tinpham5614** [comment]
> @tinpham5614 What do you think of removing the Sizes restriction for now until we can get this better defined from the Product Owner?

I agree with you to remove the Sizes restriction for now.

**Comment by intisarosman1** [comment]
> > @tinpham5614 What do you think of removing the Sizes restriction for now until we can get this better defined from the Product Owner?
> 
> I agree with you to remove the Sizes restriction for now.

I see. In that case, I'll start on another issue meanwhile.

**Comment by taylorpapke** [comment]
Hey @intisarosman1 @tinpham5614. Yes, I think the original idea was to have no fields required except for the clothing type (this is the name field in the screenshot) so it can be placed in a category. This will give the client the ability to enter an item quickly and only enter the fields that apply. This file from the backend has the correct schema and is the model carried over from the original form: https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/schemas/product.schema.ts. You will see that there is shoe size, waist and inseam for pants. You’re right, it does get difficult labeling for men vs. women vs. non-binary but this is where we could use the gender category to help. The client wasn’t too picky about this because there are a lot of clothes with missing/unreadable tags. There may be plenty of situations where all they are able to do is upload an item with type, pic and an optional description. Also, the only text field is the optional description in the original model and everything else is a preset selection with an exception for the image upload. Something we can tackle later if we want to just set them up as String text fields to start but what do you think @theGaryLarson?

**Comment by theGaryLarson** [comment]
@taylorpapke First off thank you for directing to the schema in Nest.js. @intisarosman1 I can get that ported over for you but it might take me until later on this evening. The product schema needs to be ported over to Belinda's so that we ensure the DTO is the same when being sent to the backend. The important part is having the property values and types align with the backend.

### Key Considerations
-  Product data structure on the front end must align with backend data structure
-  We need them well defined for devs to be able to work independently of other code.

**Comment by taylorpapke** [comment]
@intisarosman1 I think all of the product details will be available once https://github.com/SeattleColleges/belindas-closet-android/pull/85 gets merged in. @tinpham5614 has included an updated Product.kt file in his latest PR.
